const productArray=[
    {
        id: 1,
        name: "ChargeWorx Folding",
        prise: 50,
        newPrise: 15,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/ChargeWorx_Folding.jpg",
        categories: {
            "best selle": true,
            "Home page": true,
        },
        count: 40,
        size: "none",
        color: "none",
    },
    {
        id: 2,
        name: "Clear Case With MagSafe",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Clear_Case_With_MagSafe.jpg",
        categories: {
            "hot deal": true,
            "Home page": true,
        },
        count: 40,
        size: {
            "M": true,
        },
        color: {
            "Green": true,
            "Read": true,
        },
    },
    {
        id: 3,
        name: "HDMI Multiport Adapter",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/HDMI_Multiport_Adapter.jpg",
        categories: {
            'best seller': true,
            'Home page': true,
            "hot deal": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 4,
        name: "Mighty Mini 130 30W",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Mighty_Mini_130_30W.jpg",
        categories: {
            "hot deal": true,
            "Home page": true,
            'best seller': true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 5,
        name: "PowerBox 160 US",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/PowerBox_160_US.jpg",
        categories: {
            "best seller": true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 6,
        name: "Premium World Power",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Premium_World_Power.jpg",
        categories: {
            "hot deal": true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 7,
        name: "Thin Case For IPhone",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Thin_Case_For_IPhone.jpg",
        categories: {
            "best seller": true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 8,
        name: "Thin Smartphone Case",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Thin_Smartphone_Case.jpg",
        categories: {
            "hot deal": true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 9,
        name: "Tile Pro Bluetooth Tracker",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Tile_Pro_Bluetooth_Tracker.jpg",
        categories: {
            "best seller": true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 10,
        name: "75 Headset",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/75_Headset.jpg",
        categories: {
            "best seller": true,
            "Home page": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 11,
        name: "Windshield Smartphone Mount",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Windshield_Smartphone_Mount.jpg",
        categories: {
            "best seller": true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
    {
        id: 12,
        name: "Waterproof Wireless Charging",
        prise: 30,
        newPrise: 25,
        discription: "Being able to read a novel in another language and understand it is a huge achievement. You’ll feel accomplished the moment you read that final page, close the book, and reflect on the experience. You might find yourself at the last page faster than you thought—once you begin reading these...",
        img: "/img/product/Waterproof_Wireless-Charging.jpg",
        categories: {
            'hot deal': true,
            "Home page": true,
            "new": true,
        },
        count: 40,
        size: {
            "M": true,
            "L": true,
            "XL": true,
        },
        color: {
            'Greenr': true,
            'Read': true,
        },
    },
]
